### ISSUE TITLE
Allow for writing a stream of data to a CSV file

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/pycsvy#13]
At present, all of the data is required to be in memory (e.g. as a ``DataFrame``) before it can be written out to a CSV file. This is not a problem for small datasets, but for large ones -- or ones that are acquired over a long time period -- it is important to be able to write data as you go along (partly because of memory constraints, but also because e.g. the power might fail).

This is the sort of interface I have in mind:
```py
with csvy.StreamWriter(filename, columns=['Time', 'CH0', 'CH1'], metadata=metadata) as writer:
    while something():
        writer.write_row(time, *data)
```

**Comment by alexdewar** [comment]
Weirdly I can't set a label for this issue, but it should be labelled "enhancement".

It could also be labelled "Hacktoberfest", if we want to start using that as a label for things!

**Comment by dalonsoa** [comment]
@all-contributors please add @alexdewar  for ideas

**Comment by dalonsoa** [comment]
@AdrianDAlessandro , now that the fix for mypy is merged, you will need to update this branch to get all tests pass.
