### ISSUE TITLE
`Writer`: Add option to flush buffer more frequently

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/pycsvy#60]
As the data we are recording with `Writer` is important (e.g. experiment data) it might be useful to have the option to flush the write buffer more frequently. You can change the default buffering behaviour in Python when you call `open()`: https://docs.python.org/3/library/functions.html#open

It may be sensible to flush data with every line written. This can be achieved if the user explicitly calls `flush()` after every write, but currently this means they have to use the private `_file` member. It is probably cleaner all round if they can just set this up when they create the `Writer` object in the first place. We might even want to turn this option on by default; the performance penalty isn't likely to be high.

In a similar vein, I have also been using `os.fsync()` before closing CSV files, which tells the OS to commit the changes to disk immediately. We could do this automatically when the user enables the option to flush with every line.

What do you think @dalonsoa? @cc-a Do you have any thoughts about this?

**Comment by dalonsoa** [comment]
To be honest, it didn't cross my mind this could be a thing. I understand that this would affect only the CSV writer and not the numpy and pandas ones, right?

In any case, without knowing more on the potential drawbacks, it looks like a good idea.

**Comment by alexdewar** [comment]
Yep, it would just affect the `Writer` class.

I *think* the only drawback is that it could affect IO throughput, as you're effectively forcing Python to flush its buffers more often than it otherwise would. That said, I suspect it's very unlikely that this would be a bottleneck in practice.

Probably the sensible way to do this is to make users opt in if they want it via an argument to `__init__()`.
