### ISSUE TITLE
Implement dependabot automerge

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/pycsvy#74]
Dependabot is a tool that automatically upgrade dependencies when there's a new version. It works for, the software dependencies, but also the version of the GitHub action workflows and pre-commit.

At the moment, it just opens PR with the new versions, but if no-one keeps an eye on them, they are never merged.

Things should be arranged such that the PR related to dependabot (and pre-commit) are automatically merged if all checks pass. This is done via a workflow file, such as https://github.com/ImperialCollegeLondon/paricia/blob/main/.github/workflows/auto-merge.yml

**Comment by mikeheyns** [comment]
@dalonsoa is this a simple lift and shift from the example workflow file or are we expecting any gremlins?

**Comment by dalonsoa** [comment]
It should be a simple lifts and shift, but you never know where gremlins lure... :)

**Comment by mikeheyns** [comment]
Great - and how would you like to manage contributions? Update the infrastructure branch and push to that? May need permissions

**Comment by dalonsoa** [comment]
Nope, you create a separate branch just for this stuff and then open a PR against develop.

**Comment by dalonsoa** [comment]
You probably need to fork the repo to your own account.
