### ISSUE TITLE
Add support for `polars`

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/pycsvy#83]
## Problem

[`polars`](https://pola.rs/) has become recently a very attractive - and faster - alternative to `pandas`, so we should support it, as well. 

## Solution

Largely copying what's in place for `pandas`, implement support for reading data into a `polars` dataframe with [`read_csv`](https://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html) and from a `polars` dataframe with [`write_csv`](https://docs.pola.rs/api/python/stable/reference/api/polars.DataFrame.write_csv.html).

**Comment by AdrianDAlessandro** [comment]
I'll take this. I believe the best way to do this is to start using [narwhals](https://github.com/narwhals-dev/narwhals/tree/main) (which provides a dataframe-agnostic API). There doesn't appear to be support for a read_csv in Narwhals, but there is a [write_csv](https://narwhals-dev.github.io/narwhals/api-reference/dataframe/#narwhals.dataframe.DataFrame.write_csv) that we can use.

**Comment by dalonsoa** [comment]
If there's no `read_csv`, how are you planning to proceed for creating `polars` dataframes?

**Comment by AdrianDAlessandro** [comment]
I will implement it using the read_csv from polars. This will probably be two separate PRs, one for read and one for write.

**Comment by dalonsoa** [comment]
But that will add two dependencies rather than just one, `polars`. Isn't it a bit overkilling to use `narwhals` in this case, specially considering that it only implements half of what we need?

**Comment by AdrianDAlessandro** [comment]
I'll do it just with polars for now and open a separate issue about narwhals
