### ISSUE TITLE
Include a native Python dict `read` function

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/pycsvy#91]
Since the most basic version of this package only requires the pyyaml dependency, there should be a basic `read` function that returns a native Python type.

There is currently a `read_to_list` function (that isn't exposed as a top-level function), that returns a nested list. But that isn't in the most developer friendly format because it has a mix of column headers and data in the list. A dictionary type feels more appropriate.

The dictionary could be structured with 2 keys, "columns" and "data", with "data" being a 2D nested list. Or it could have the columns names as keys and the values each being a list for that column.

**Comment by Kaos599** [comment]
can i try working on this @AdrianDAlessandro

**Comment by AdrianDAlessandro** [comment]
Sure!

**Comment by Kaos599** [comment]
@AdrianDAlessandro I have tried to address the issue in the following [PR](https://github.com/ImperialCollegeLondon/pycsvy/pull/131).
